import { fold } from '@shared/extras'

/**
 * Words to find the emoji picker's emoji by, in English and Vietnamese (searched without case or accents).
 * Keyed without U+FE0F, so '❤️' and '❤' look up the same words. Emoji not listed are found by their group's words.
 */
const WORDS: Record<string, string> = {
  // smileys
  '😀': 'grin grinning smile happy cười toe toét vui',
  '😃': 'smile happy big eyes cười vui',
  '😄': 'smile happy laugh cười vui',
  '😁': 'grin beaming teeth cười nhe răng',
  '😆': 'laugh squint haha cười híp mắt',
  '😅': 'sweat smile nervous cười đổ mồ hôi ngại',
  '🤣': 'rofl rolling laugh lol haha cười lăn lộn',
  '😂': 'joy laugh tears lol haha cười ra nước mắt',
  '🙂': 'slight smile cười mỉm',
  '😉': 'wink nháy mắt',
  '😊': 'blush smile happy cười ngượng vui',
  '😇': 'angel halo innocent thiên thần ngoan',
  '🥰': 'smiling hearts love adore yêu thương say nắng',
  '😍': 'heart eyes love crush mắt trái tim mê',
  '🤩': 'star struck wow excited mắt sao phấn khích',
  '😘': 'kiss blow hôn gió',
  '😗': 'kiss hôn',
  '😚': 'kiss closed eyes hôn',
  '😙': 'kiss smile hôn',
  '🥲': 'smile tear touched cười rưng rưng cảm động',
  '😋': 'yum delicious tasty ngon',
  '😛': 'tongue lè lưỡi',
  '😜': 'wink tongue crazy lè lưỡi nháy mắt',
  '🤪': 'zany crazy goofy điên khùng nhây',
  '😝': 'squint tongue lè lưỡi',
  '🤑': 'money rich tiền giàu',
  '🤗': 'hug hugging ôm',
  '🤭': 'oops giggle hand over mouth che miệng cười khúc khích',
  '🤫': 'shush quiet secret suỵt im lặng bí mật',
  '🤔': 'thinking hmm think suy nghĩ',
  '🫡': 'salute yes sir chào nghiêm',
  '🤐': 'zipper mouth secret khóa miệng',
  '🤨': 'raised eyebrow suspicious nghi ngờ nhướng mày',
  '😐': 'neutral meh bình thường',
  '😑': 'expressionless blank vô cảm',
  '😶': 'no mouth speechless câm nín',
  '😏': 'smirk cười đểu nhếch mép',
  '😒': 'unamused annoyed chán bực',
  '🙄': 'eye roll whatever đảo mắt',
  '😬': 'grimace awkward nhăn mặt ngượng',
  '🤥': 'lying liar pinocchio nói dối',
  '😌': 'relieved calm nhẹ nhõm',
  '😔': 'pensive sad buồn',
  '😪': 'sleepy buồn ngủ',
  '🤤': 'drool thèm chảy nước miếng',
  '😴': 'sleep sleeping zzz ngủ',
  '😷': 'mask sick ốm khẩu trang',
  '🤒': 'fever thermometer sick sốt ốm',
  '🤕': 'hurt bandage injured đau bị thương',
  '🤢': 'nauseated sick buồn nôn',
  '🤮': 'vomit puke nôn ói',
  '🥵': 'hot sweating nóng',
  '🥶': 'cold freezing lạnh',
  '🥴': 'woozy drunk say xỉn chóng mặt',
  '😵': 'dizzy chóng mặt',
  '🤯': 'mind blown shocked sốc nổ não',
  '🤠': 'cowboy cao bồi',
  '🥳': 'party celebrate birthday tiệc sinh nhật ăn mừng',
  '🥸': 'disguise incognito cải trang',
  '😎': 'cool sunglasses ngầu kính râm',
  '🤓': 'nerd geek mọt sách',
  '🧐': 'monocle inspect soi',
  '😕': 'confused bối rối',
  '😟': 'worried lo lắng',
  '🙁': 'frown sad buồn',
  '😮': 'open mouth surprised wow ngạc nhiên',
  '😯': 'hushed surprised ngạc nhiên',
  '😲': 'astonished shocked kinh ngạc',
  '😳': 'flushed embarrassed đỏ mặt ngượng',
  '🥺': 'pleading puppy eyes please năn nỉ mắt cún',
  '🥹': 'holding back tears touched cảm động rưng rưng',
  '😦': 'frown open mouth hoảng',
  '😧': 'anguished đau khổ',
  '😨': 'fearful scared sợ',
  '😰': 'anxious sweat lo âu',
  '😥': 'sad relieved thất vọng',
  '😢': 'cry tear sad khóc buồn',
  '😭': 'sob loudly crying khóc to nức nở',
  '😱': 'scream fear horror hét sợ hãi',
  '😖': 'confounded khó chịu',
  '😣': 'persevere cố gắng',
  '😞': 'disappointed thất vọng',
  '😓': 'downcast sweat mệt',
  '😩': 'weary tired mệt mỏi',
  '😫': 'tired exhausted kiệt sức',
  '🥱': 'yawn bored ngáp chán',
  '😤': 'triumph huff hừ tức',
  '😡': 'pout angry rage giận tức',
  '😠': 'angry mad giận',
  '🤬': 'cursing swearing chửi',
  '😈': 'devil smiling evil quỷ',
  '👿': 'devil angry imp quỷ giận',
  '💀': 'skull dead chết đầu lâu',
  '💩': 'poop shit cứt phân',
  '🤡': 'clown hề',
  '👻': 'ghost boo ma',
  '👽': 'alien người ngoài hành tinh',
  '🤖': 'robot người máy',
  // gestures and people
  '👍': 'thumbs up like ok yes like đồng ý',
  '👎': 'thumbs down dislike no không thích',
  '👋': 'wave hello hi bye vẫy tay chào',
  '🤚': 'raised back hand giơ tay',
  '🖐': 'hand fingers splayed bàn tay',
  '✋': 'raised hand stop high five dừng',
  '🖖': 'vulcan salute',
  '👌': 'ok okay perfect được',
  '🤌': 'pinched fingers italian chụm tay',
  '🤏': 'pinch small little một chút',
  '✌': 'victory peace hòa bình chiến thắng',
  '🤞': 'crossed fingers luck may mắn',
  '🫰': 'finger heart money tim ngón tay',
  '🤟': 'love you gesture yêu',
  '🤘': 'rock horns',
  '🤙': 'call me shaka gọi',
  '👈': 'point left trái',
  '👉': 'point right phải',
  '👆': 'point up lên',
  '👇': 'point down xuống',
  '☝': 'index up one một',
  '👏': 'clap applause vỗ tay',
  '🙌': 'raising hands hooray celebrate hoan hô',
  '🫶': 'heart hands love tim tay',
  '👐': 'open hands mở tay',
  '🤲': 'palms up together chắp tay',
  '🤝': 'handshake deal bắt tay',
  '🙏': 'pray please thanks cảm ơn cầu nguyện xin',
  '✍': 'writing hand viết',
  '💅': 'nail polish sơn móng',
  '🤳': 'selfie tự sướng',
  '💪': 'muscle strong flex mạnh cơ bắp cố lên',
  '🦾': 'mechanical arm tay máy',
  '🧠': 'brain smart não thông minh',
  '👀': 'eyes look see nhìn mắt',
  '👁': 'eye mắt',
  '👅': 'tongue lưỡi',
  '👄': 'mouth lips môi miệng',
  '🫂': 'people hugging hug ôm',
  '👶': 'baby em bé',
  '🧑': 'person người',
  '👩': 'woman phụ nữ',
  '👨': 'man đàn ông',
  '🧑‍💻': 'technologist coder developer lập trình viên máy tính',
  '🧑‍🎨': 'artist họa sĩ',
  '🧑‍🍳': 'cook chef đầu bếp nấu ăn',
  '🧑‍🎓': 'student graduate sinh viên tốt nghiệp',
  '💃': 'dance dancer woman nhảy múa',
  '🕺': 'dance dancer man nhảy',
  '🧘': 'yoga meditate thiền',
  '🏃': 'run running chạy',
  '🚶': 'walk walking đi bộ',
  // hearts and celebration
  '❤': 'red heart love tim đỏ yêu',
  '🧡': 'orange heart tim cam',
  '💛': 'yellow heart tim vàng',
  '💚': 'green heart tim xanh lá',
  '💙': 'blue heart tim xanh dương',
  '💜': 'purple heart tim tím',
  '🖤': 'black heart tim đen',
  '🤍': 'white heart tim trắng',
  '🤎': 'brown heart tim nâu',
  '💔': 'broken heart tim vỡ thất tình',
  '❤‍🔥': 'heart on fire passion tim cháy',
  '❤‍🩹': 'mending heart healing tim băng bó chữa lành',
  '💕': 'two hearts love tim yêu',
  '💞': 'revolving hearts tim',
  '💓': 'beating heart tim đập',
  '💗': 'growing heart tim',
  '💖': 'sparkling heart tim lấp lánh',
  '💘': 'heart arrow cupid tim mũi tên',
  '💝': 'heart ribbon gift tim quà',
  '💟': 'heart decoration tim',
  '♥': 'heart suit tim',
  '💋': 'kiss lips hôn môi',
  '💌': 'love letter thư tình',
  '💐': 'bouquet flowers bó hoa',
  '🌹': 'rose flower hoa hồng',
  '🌷': 'tulip flower hoa tulip',
  '🌸': 'cherry blossom flower hoa anh đào',
  '💮': 'white flower hoa trắng',
  '🏵': 'rosette flower hoa',
  '🌺': 'hibiscus flower hoa dâm bụt',
  '🌻': 'sunflower hoa hướng dương',
  '🌼': 'blossom flower hoa cúc',
  '✨': 'sparkles shiny magic lấp lánh',
  '🌟': 'glowing star ngôi sao',
  '💫': 'dizzy star sao',
  '⭐': 'star ngôi sao',
  '🌈': 'rainbow cầu vồng',
  '🔥': 'fire hot lit lửa cháy',
  '💥': 'boom collision nổ',
  '🎉': 'party popper tada congrats celebrate chúc mừng tiệc',
  '🎊': 'confetti ball celebrate chúc mừng',
  '🎈': 'balloon bóng bay',
  '🎁': 'gift present quà',
  '🎀': 'ribbon bow nơ',
  '🏆': 'trophy winner champion cúp vô địch',
  '🥇': 'gold medal first huy chương vàng nhất',
  '🎯': 'target bullseye mục tiêu',
  '🍀': 'four leaf clover luck may mắn cỏ',
  // animals and nature
  '🐶': 'dog puppy chó cún',
  '🐱': 'cat kitty mèo',
  '🐭': 'mouse chuột',
  '🐹': 'hamster chuột',
  '🐰': 'rabbit bunny thỏ',
  '🦊': 'fox cáo',
  '🐻': 'bear gấu',
  '🐼': 'panda gấu trúc',
  '🐨': 'koala gấu túi',
  '🐯': 'tiger hổ cọp',
  '🦁': 'lion sư tử',
  '🐮': 'cow bò',
  '🐷': 'pig heo lợn',
  '🐸': 'frog ếch',
  '🐵': 'monkey khỉ',
  '🐔': 'chicken gà',
  '🐧': 'penguin chim cánh cụt',
  '🐦': 'bird chim',
  '🐤': 'chick gà con',
  '🦆': 'duck vịt',
  '🦅': 'eagle đại bàng',
  '🦉': 'owl cú',
  '🦇': 'bat dơi',
  '🐺': 'wolf sói',
  '🐴': 'horse ngựa',
  '🦄': 'unicorn kỳ lân',
  '🐝': 'bee ong',
  '🦋': 'butterfly bướm',
  '🐢': 'turtle rùa',
  '🐍': 'snake rắn',
  '🐙': 'octopus bạch tuộc',
  '🦀': 'crab cua',
  '🐠': 'fish cá',
  '🐬': 'dolphin cá heo',
  '🐳': 'whale cá voi',
  '🦈': 'shark cá mập',
  '🐘': 'elephant voi',
  '🌵': 'cactus xương rồng',
  '🎄': 'christmas tree giáng sinh noel',
  '🌴': 'palm tree beach cây dừa',
  '🍁': 'maple leaf autumn lá phong mùa thu',
  '🌊': 'wave ocean sea sóng biển',
  '🌙': 'moon night trăng đêm',
  '☀': 'sun sunny nắng mặt trời',
  '⛅': 'cloud sun mây',
  '❄': 'snow cold tuyết lạnh',
  // food and drink
  '🍜': 'pho noodle ramen soup bún phở mì',
  '🍲': 'hot pot stew lẩu',
  '🍛': 'curry rice cà ri',
  '🍚': 'rice cơm',
  '🍙': 'rice ball onigiri cơm nắm',
  '🍱': 'bento cơm hộp',
  '🥟': 'dumpling bánh bao há cảo',
  '🍣': 'sushi',
  '🍤': 'shrimp tempura tôm',
  '🍔': 'burger hamburger',
  '🍟': 'fries khoai tây chiên',
  '🍕': 'pizza',
  '🌭': 'hot dog xúc xích',
  '🥪': 'sandwich bánh mì',
  '🌮': 'taco',
  '🥗': 'salad rau',
  '🍳': 'egg cooking trứng chiên',
  '🧀': 'cheese phô mai',
  '🍗': 'chicken leg gà rán',
  '🥩': 'steak meat thịt',
  '🌽': 'corn bắp ngô',
  '🥕': 'carrot cà rốt',
  '🍅': 'tomato cà chua',
  '🥑': 'avocado bơ',
  '🍎': 'apple táo',
  '🍊': 'orange cam',
  '🍋': 'lemon chanh',
  '🍌': 'banana chuối',
  '🍉': 'watermelon dưa hấu',
  '🍇': 'grapes nho',
  '🍓': 'strawberry dâu',
  '🍒': 'cherry anh đào',
  '🥭': 'mango xoài',
  '🍍': 'pineapple dứa thơm',
  '🥥': 'coconut dừa',
  '🍰': 'cake bánh kem',
  '🎂': 'birthday cake bánh sinh nhật',
  '🧁': 'cupcake bánh',
  '🍩': 'donut bánh vòng',
  '🍪': 'cookie bánh quy',
  '🍫': 'chocolate sô cô la',
  '🍬': 'candy kẹo',
  '🍭': 'lollipop kẹo mút',
  '☕': 'coffee cà phê cafe',
  '🍵': 'tea trà',
  '🧋': 'bubble tea boba milk tea trà sữa trân châu',
  '🥤': 'soda drink nước ngọt',
  '🍺': 'beer bia',
  '🍻': 'cheers beers bia dzô',
  '🥂': 'cheers champagne nâng ly',
  '🍷': 'wine rượu vang',
  '🍸': 'cocktail',
  // activity and travel
  '⚽': 'soccer football bóng đá',
  '🏀': 'basketball bóng rổ',
  '🎾': 'tennis quần vợt',
  '🏸': 'badminton cầu lông',
  '🏓': 'ping pong bóng bàn',
  '🎮': 'video game controller trò chơi chơi game',
  '🎲': 'dice xúc xắc',
  '🎨': 'art paint palette vẽ',
  '🎬': 'movie film phim',
  '🎤': 'microphone karaoke sing hát',
  '🎧': 'headphones music nghe nhạc',
  '🎸': 'guitar đàn',
  '📸': 'camera flash photo chụp ảnh',
  '✈': 'airplane plane flight máy bay',
  '🚀': 'rocket launch tên lửa',
  '🚗': 'car ô tô xe hơi',
  '🚌': 'bus xe buýt',
  '🚲': 'bicycle bike xe đạp',
  '🛵': 'scooter motorbike xe máy',
  '🏖': 'beach biển bãi biển',
  '🧳': 'luggage travel vali du lịch',
  // objects
  '💡': 'idea light bulb ý tưởng bóng đèn',
  '📱': 'phone mobile điện thoại',
  '💻': 'laptop computer máy tính',
  '⏰': 'alarm clock báo thức đồng hồ',
  '🔋': 'battery pin',
  '💰': 'money bag tiền',
  '💳': 'credit card thẻ',
  '💎': 'diamond gem kim cương',
  '📦': 'package box gói hàng hộp',
  '📝': 'memo note ghi chú',
  '📅': 'calendar date lịch',
  '📌': 'pin ghim',
  '🔒': 'lock khóa',
  '🔑': 'key chìa khóa',
  '🛒': 'shopping cart mua sắm',
  '🛍': 'shopping bags mua sắm',
  '👑': 'crown king queen vương miện',
  '💍': 'ring engagement nhẫn',
  // symbols
  '✅': 'check done yes ok xong đúng',
  '❌': 'cross no wrong sai không',
  '❓': 'question hỏi',
  '❗': 'exclamation important chú ý',
  '💯': 'hundred perfect một trăm điểm',
  '⚠': 'warning cảnh báo',
  '🚫': 'prohibited forbidden no cấm',
  '🆗': 'ok button',
  '🆕': 'new mới',
  '🔄': 'repeat refresh lặp lại',
  '🔊': 'loud speaker volume âm thanh to',
  '🔇': 'mute tắt tiếng',
  '🔔': 'bell notification chuông',
  '💤': 'zzz sleep ngủ',
  '💬': 'speech bubble chat tin nhắn',
  '💭': 'thought bubble suy nghĩ',
  '🏁': 'finish flag cờ đích',
  '🏳‍🌈': 'rainbow flag pride cờ cầu vồng',
  '🇻🇳': 'vietnam flag việt nam cờ',
  '🇺🇸': 'usa america flag mỹ cờ',
  '🇬🇧': 'uk britain flag anh cờ',
  '🇯🇵': 'japan flag nhật cờ',
  '🇰🇷': 'korea flag hàn quốc cờ',
  '🇫🇷': 'france flag pháp cờ',
  '🇩🇪': 'germany flag đức cờ'
}

/** Words for each group of the picker: an emoji with no words of its own is still found by these. */
const GROUP_WORDS: Record<string, string> = {
  smileys: 'smiley face emotion mặt cảm xúc biểu cảm',
  gestures: 'hand gesture people body tay cử chỉ người',
  hearts: 'heart love celebration party flower tim yêu tình yêu tiệc hoa',
  animals: 'animal nature plant weather động vật con vật thiên nhiên cây thời tiết',
  food: 'food drink đồ ăn thức ăn món ăn đồ uống',
  activity: 'activity sport game music travel vehicle hoạt động thể thao trò chơi âm nhạc du lịch xe',
  objects: 'object thing tech đồ vật đồ dùng',
  symbols: 'symbol sign flag ký hiệu biểu tượng dấu cờ'
}

const bare = (emoji: string): string => emoji.replace(/\uFE0F/g, '')
const wordsOf = (text: string): string[] => fold(text).split(/\s+/)
// Folded once here, not on every keystroke.
const FOLDED = new Map(Object.entries(WORDS).map(([emoji, words]) => [emoji, wordsOf(words)]))
const FOLDED_GROUPS = new Map(Object.entries(GROUP_WORDS).map(([group, words]) => [group, wordsOf(words)]))
const NONE: string[] = []

/**
 * The emoji matching a search, best first: every word typed must start one of the emoji's words (or its group's).
 * Its own words count over its group's, a whole word over a prefix; typing the emoji itself finds it too.
 */
export function searchEmoji(query: string, groups: ReadonlyArray<{ id: string; emoji: readonly string[] }>): string[] {
  const q = query.trim()
  if (!q) return []
  const tokens = wordsOf(q)
  const scored: Array<{ emoji: string; score: number }> = []
  const seen = new Set<string>()
  for (const group of groups) {
    const groupWords = FOLDED_GROUPS.get(group.id) ?? NONE
    for (const emoji of group.emoji) {
      if (seen.has(emoji)) continue
      seen.add(emoji)
      if (bare(emoji).includes(bare(q))) {
        scored.push({ emoji, score: 1000 })
        continue
      }
      const own = FOLDED.get(bare(emoji)) ?? NONE
      let score = 0
      for (const token of tokens) {
        const best = own.includes(token) ? 3 : own.some((w) => w.startsWith(token)) ? 2 : groupWords.some((w) => w.startsWith(token)) ? 1 : 0
        if (!best) {
          score = 0
          break
        }
        score += best
      }
      if (score) scored.push({ emoji, score })
    }
  }
  // Array sort is stable: equal scores keep the picker's order.
  return scored.sort((a, b) => b.score - a.score).map((s) => s.emoji)
}
